class CONST:
    SEM_DADOS = "SEM DADOS"
    REPROVADO = "REPROVADO"
    ABONADO = "ABONADO"
    NOME_AUSENCIA_ABONADA = 'Ausência Abonada'
    NOME_CONSULTA_MEDICA = 'Consulta Médica'
    COLUNAS_AUSENCIA_ABONADA = ['INDEX','TICKET','REGISTRO','DATA','HORA_INICIAL','HORA_FINAL','PT_BAL00','TIPO_JORNADA','HORAS_TEORICO','TEMPO_TEORICO','PERIODO1','PERIODO2','AUSENCIA','PRESENCA','QTD_MARCACOES','MARCACOES','RESULTADO','SOLUCAO_RESPOSTA']
    COLUNAS_CONSULTA_MEDICA = ['INDEX','TICKET','REGISTRO','DATA','HORA_INICIAL','PT_BAL00','TIPO_JORNADA','HORAS_TEORICO','TEMPO_TEORICO','PERIODO1','PERIODO2','AUSENCIA','PRESENCA','QTD_MARCACOES','MARCACOES','RESULTADO','SOLUCAO_RESPOSTA']
