class CONST:
    SEM_DADOS = "SEM DADOS"
    nomeAusenciaAbonada = 'Ausência Abonada'
    nomeConsultaMedica = 'Consulta Médica'
    colunasAusenciaAbonada = ['INDEX','TICKET','REGISTRO','DATA','HORA_INICIAL','HORA_FINAL','PT_BAL00','TIPO_JORNADA','HORAS_TEORICO','TEMPO_TEORICO','PERIODO1','PERIODO2','AUSENCIA','PRESENCA','QTD_MARCACOES','MARCACOES','RESULTADO','SOLUCAO_RESPOSTA']
    colunasConsultaMedica = ['INDEX','TICKET','REGISTRO','DATA','HORA_INICIAL','PT_BAL00','TIPO_JORNADA','HORAS_TEORICO','TEMPO_TEORICO','PERIODO1','PERIODO2','AUSENCIA','PRESENCA','QTD_MARCACOES','MARCACOES','RESULTADO','SOLUCAO_RESPOSTA']
